# Generated by Django 3.0.4 on 2020-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='typ',
            field=models.CharField(choices=[('Extra', 'Extra'), ('Study', 'Study'), ('Entertainment', 'Entertainment')], default='Extra', max_length=100),
        ),
    ]
