# Generated by Django 3.0.4 on 2020-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_category_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='file_type',
            field=models.CharField(choices=[('video', 'video'), ('pic', 'pic'), ('other', 'other'), ('pdf', 'pdf'), ('docx', 'docx')], default='video', max_length=100),
        ),
        migrations.AddField(
            model_name='extra',
            name='file_type',
            field=models.CharField(choices=[('video', 'video'), ('pic', 'pic'), ('other', 'other'), ('pdf', 'pdf'), ('docx', 'docx')], default='video', max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='file_type',
            field=models.CharField(choices=[('video', 'video'), ('pic', 'pic'), ('other', 'other'), ('pdf', 'pdf'), ('docx', 'docx')], default='video', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='typ',
            field=models.CharField(choices=[('Extra', 'Extra'), ('Entertainment', 'Entertainment'), ('Study', 'Study')], default='Extra', max_length=100),
        ),
    ]
